# ch 12. 프로미스 개념부터 활용까지

## Promise

: JS에서 제공하는 비동기를 간편하게 처리할 수 있게 해주는 Object

- 정해진 장시간의 기능을 수행하고 나서, 정상적으로 기능이 수행이 되어 졌다면

→ 성공의 메세지와 함께 처리된 결과값 (resolve - then) 

- 기능을 수행하다가 예상치 못한 난관에 빠져 정상적으로 실행되지 않았다면

→ 에러 메세지 전달 (reject - catch) 

**Point** 

1. **State (상태)  : 기능 수행 중(pending) 기능 수행 후 | 성공?(fullfilled) / 실패?(rejected)** 
2. **Producer(제공) - Consumer(소비)** 

---

## 1. Producer : Promise 만들기

```jsx
const promise = new Promise((resolve, reject) => {
    // heavy한 일을 진행 ex) 네트워크로 부터 데이터를 받아옴 (비동기적으로 진행)
    console.log('doing Something'); // 바로 실행 
    setTimeout(()=>{
        resolve('ellie'); // 성공! , 당장 실행 X , then으로 호출할 때 수행
        // reject(new Error('no found network'));
    },2000);
});
```

→ 시간이 걸리는 일들은 동기적으로 수행하게 되면 Heavy 할 수록 다음에 실행되어야 하는 일들은 계속 실행이 안되기에 매우 비효율적 : 이를 Promise를 통해서 비동기적으로 수행한다. 

→ 새로운 프로미스를 만들 때는 executor 함수는 자동적으로 바로 (동기적으로) 실행된다. 

**(그냥, 프로미스 생성할 때 까지는 동기적으로 수행된다고 이해)**

---

## 2. Consumer : then(성공), catch(실패), finally(성공/실패 상관X)

```jsx
promise
    .then((value)=>{ // value에는 resolve() 괄호 안의 값이 전달, 콜백함수에서 전달된 값이 들어가게 된다.
    console.log(value);
    })
    .catch((value)=>{ // value에는 reject() 괄호 안의 값이 전달, 콜백함수에서 전달된 값이 들어가게 된다.
        console.log(value);
    })
    .finally(()=>{ // 성공 실패와 상관없이 프로미스에 붙어서 출력 가능.
        console.log('프로미스 끝!');
    })
```

- then.catch.finally → 묶고 묶을 수 있어서 이를 **Promise Chaining** 이라고 한다.
- 이때는 비동기로 실행된다.

---

## 3. Promise Chaining

```jsx
// 3. Promise Chaining
const fetchNumber = new Promise((resolve, reject)=>{
    setTimeout(()=>{
        resolve (1)
    },1000)
})

fetchNumber
    .then((value)=>value*2) //((value)=>{return value*2}) //2
    .then((value)=>value*3) //((value)=>{return value*3}) //6
    .then((value)=>{ // 6이 전달 1초 후 6-1을 전달 , then에서는 값을 전달해도 되고 새로운 Promise를 리턴해도 된다.
        return new Promise(((resolve, reject) => {
            setTimeout(()=>resolve(value-1),1000)
        }))
    })
    .then((value)=>console.log(value)); // 5 출력
```

- 우리가 이전에 보았던 배열 함수에서 여러 개의 API들을 이어서 사용하는 것과 같은 원리
- then, catch 등을 이어서 계속 사용 할 수 있다.

> **then 에서는 값을 전달 해도 되고, 새로운 Promise를 리턴 해도 된다.**

---

## 4. Error Handling

**→ 만약  Promise Chaining 중 Error 가 발생한다면?** 

**새로운 Promise를 리턴하는 함수**

- **Producer**

```jsx
const getHen = () =>
    new Promise((resolve, reject) => {
        setTimeout(()=>{resolve('hen')},1000);
    })

// getEgg에서 reject로써 에러 반환 
const getEgg = (hen)=>
    new Promise(((resolve, reject) => {
        setTimeout(()=>reject(new Error(`${hen} + egg`)),1000);
        }))

const cook = (egg) =>
    new Promise(((resolve, reject) => {
        setTimeout(()=>resolve(`${egg} + cook`),1000);
    }))
```

- **Consumer**

```jsx
getHen()
	.then((hen)=> getEgg(hen)) // getHen에서 얻은 값을 getEgg()에 넣어준다. 
	.then((egg)=> cook(egg)) // reject이기 때문에 에러 발생 
	.then((value) => console.log(value)) 
```

→ getEgg() 에서는 reject이므로 에러 발생 

**⇒ catch 를 통해서 Error Control 이 필수적이다.** 

- **Error Handling (use catch)**

```jsx
getHen()
	.then((hen)=> getEgg(hen)) // getHen에서 얻은 값을 getEgg()에 넣어준다. 
	.then((egg)=> cook(egg)) //getEgg에서 얻은 값을 cook()에 넣어준다.
	.catch((error)=>{return 'bread';}) // 만약 에러가 났으면 여기서 이전 값들을 bread로 대체  
	.then((value) => console.log(value)) // cook에서 나온 값을 출력한다. 
	.catch((message)=>console.log(message)); //에러 메세지가 나오면 마지막에서 출력한다.
```

**⇒ reject가 발생 할 것을 대비하여 , catch를 활용하여 어떻게 막을 지?!**  

---

## Promise 활용 로그인 구현

- 이전 CallBack을 응용

```jsx
// 콜백 헬 -> 프로미스 체이닝
'use strict';
class UserStorage {
    loginUser(id, password) {
        return new Promise(((resolve, reject) => {
            setTimeout(()=>{
                if (id === 'ellie' && password === 'dream' || id === 'coder' && password === 'academy'){
                    resolve(id);
                }else {
                    reject(new Error('조회된 ID가 없습니다.'));
                }
            },2000);
        }))
    }

    getRoles(user){
        return new Promise((resolve, reject) => {
            setTimeout(()=>{
                if (user === 'ellie'){
                    resolve({name : 'ellie', role: 'admin'});
                }else {
                    reject(new Error(`${user}님 께서는 접근 권한이 존재하지 않습니다.`));
                }
            },1000);
        })
    }
}

const id = prompt('ID를 입력하세요');
const password = prompt('PassWord를 입력하세요');

const newUser = new UserStorage();
newUser.loginUser(id , password) // 로그인 성공하면
.then((user) => newUser.getRoles(user)) // id를 getRoles에 전달
.then((message)=> alert(`${message.name}님! 당신은 ${message.role}이 있습니다.`))
.catch(alert);
```

- onSuccess, onError 등을 줄일 수 있어서 획기적이다.
- resolve, reject등을 활용하여 이를 구현할 수 있어서 비동기 콜백 지옥에서 탈출